# RabbitMQ Configuration File

# Network and Protocol
listeners.tcp.default = 5672
management.tcp.port = 15672

# Memory limits
vm_memory_high_watermark.relative = 0.6

# Disk space monitoring
disk_free_limit.absolute = 500MB

# Clustering
cluster_partition_handling = autoheal

# Management plugin
management.load_definitions = /etc/rabbitmq/definitions.json

# Enabling plugins
management.enabled = true
